/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.prova;

import com.sun.org.apache.xerces.internal.parsers.IntegratedParserConfiguration;
import java.awt.Color;
import java.util.Random;


/**
 *
 * @author Pai
 */
public class Provinha extends javax.swing.JFrame {
   
      
      // Pegar a quantidade de cliques do botão
      Integer cliques = 0;
      
      
      // Armazenar os números que foram sortados
      Integer guardar1 = 0;
      Integer guardar2 = 0;
      Integer guardar3 = 0;
      
      // Fazer o maximo
      Integer maximo = 0;
      Integer maximo2 = 0;
      Integer maximo3 = 0;
            
      // Adicionar o maximo
      Integer contMax = 0;
      Integer contMax2 = 0;
      Integer contMax3 = 0;
      
      // Fazer o minimo
      Integer minimo = 100;
      Integer minimo2 = 100;
      Integer minimo3 = 100;
      
      // contar o minimo
      Integer contMin = 0;
      Integer contMin2 = 0;
      Integer contMin3 = 0;
    /**
     * Creates new form Provinha
     */
    public Provinha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpu = new javax.swing.JLabel();
        prgCpu = new javax.swing.JProgressBar();
        lblDisco = new javax.swing.JLabel();
        prgDisco = new javax.swing.JProgressBar();
        lblMemoria = new javax.swing.JLabel();
        prgMemoria = new javax.swing.JProgressBar();
        btnFazer = new javax.swing.JButton();
        lblCpu2 = new javax.swing.JLabel();
        lblMaximo = new javax.swing.JLabel();
        txtMaximo = new javax.swing.JTextField();
        lblMedia = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        lblMinimo = new javax.swing.JLabel();
        txtMinimo = new javax.swing.JTextField();
        lblDisco2 = new javax.swing.JLabel();
        lblMaximo2 = new javax.swing.JLabel();
        txtMaximo2 = new javax.swing.JTextField();
        lblMedia2 = new javax.swing.JLabel();
        txtMedia2 = new javax.swing.JTextField();
        lblMinimo2 = new javax.swing.JLabel();
        txtMinimo2 = new javax.swing.JTextField();
        txtMaximo3 = new javax.swing.JTextField();
        lblMedia3 = new javax.swing.JLabel();
        txtMedia3 = new javax.swing.JTextField();
        lblMinimo3 = new javax.swing.JLabel();
        txtMinimo3 = new javax.swing.JTextField();
        lblMemoria2 = new javax.swing.JLabel();
        lblMaximo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCpu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCpu.setText("CPU:");

        lblDisco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDisco.setText("Disco:");

        lblMemoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMemoria.setText("Memória:");

        btnFazer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFazer.setText("Fazer leitura de dados");
        btnFazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerActionPerformed(evt);
            }
        });

        lblCpu2.setText("CPU:");

        lblMaximo.setText("Máximo:");

        txtMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximoActionPerformed(evt);
            }
        });

        lblMedia.setText("Média:");

        lblMinimo.setText("Mínimo:");

        lblDisco2.setText("Disco:");

        lblMaximo2.setText("Máximo:");

        txtMaximo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximo2ActionPerformed(evt);
            }
        });

        lblMedia2.setText("Média:");

        lblMinimo2.setText("Mínimo:");

        txtMaximo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximo3ActionPerformed(evt);
            }
        });

        lblMedia3.setText("Média:");

        lblMinimo3.setText("Mínimo:");

        txtMinimo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimo3ActionPerformed(evt);
            }
        });

        lblMemoria2.setText("Memória");

        lblMaximo3.setText("Máximo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCpu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prgCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDisco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblMemoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFazer)
                            .addComponent(prgMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMedia3)
                                    .addComponent(lblMinimo3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMemoria2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMaximo3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaximo3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedia3)
                                    .addComponent(txtMinimo3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDisco2)
                                    .addComponent(lblCpu2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMedia)
                                            .addComponent(lblMaximo)
                                            .addComponent(lblMinimo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(txtMinimo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMedia2)
                                            .addComponent(lblMaximo2)
                                            .addComponent(lblMinimo2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaximo2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMedia2)
                                            .addComponent(txtMinimo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpu)
                    .addComponent(prgCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDisco)
                    .addComponent(prgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMemoria)
                    .addComponent(prgMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnFazer)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpu2)
                    .addComponent(lblMaximo)
                    .addComponent(txtMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedia)
                    .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimo)
                    .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisco2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaximo2)
                            .addComponent(txtMaximo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedia2)
                            .addComponent(txtMedia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinimo2)
                            .addComponent(txtMinimo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaximo3)
                    .addComponent(txtMaximo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMemoria2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedia3)
                    .addComponent(txtMedia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimo3)
                    .addComponent(txtMinimo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerActionPerformed
        // TODO add your handling code here:
         // Gerar números Aleátórios
        Random gerador1 = new Random();
       Integer sortear1 = gerador1.nextInt(101);
     Random gerador2 = new Random();
     Integer sortear2 = gerador2.nextInt(101);
      Random gerador3 = new Random();
      Integer sortear3 = gerador3.nextInt(101);
      
      cliques++; 
      
      // Fazer a média 
     Integer somaMedia1 = guardar1 = guardar1 + sortear1 / cliques;
     Integer somaMedia2 = guardar2 = guardar2 + sortear2 / cliques;
     Integer somaMedia3 = guardar3 = guardar3 + sortear3 / cliques;
     
     
     
     // Fazer o máximo
        if (sortear1 > maximo) {
            maximo = sortear1;
            contMax++;
        }
        
        if (sortear2 > maximo2) {
            maximo2 = sortear2;
            contMax2++;
        }
        
        if (sortear3 > maximo3) {
            maximo3 = sortear3;
            contMax3++;
        }
     // Fazer o mínimo 
        if (sortear1 < minimo) {
            minimo = sortear1;
            contMin++;
        }
        if (sortear2 < minimo2) {
            minimo2 = sortear2;
            contMin2++;
        }
        if (sortear3 < minimo3) {
            minimo3 = sortear3;
            contMin3++;
        }
      
        prgCpu.setStringPainted(true);
        prgCpu.setString(String.format("%d%%", sortear1));
        prgCpu.setForeground(Color.blue);
        prgCpu.setValue(sortear1);
        
        txtMaximo.setText(String.format("%d", maximo));
        txtMaximo2.setText(String.format("%d", maximo2));
        txtMaximo3.setText(String.format("%d", maximo3));
        
        txtMedia.setText(String.format("%d", somaMedia1));
        txtMedia2.setText(String.format("%d", somaMedia2));
        txtMedia3.setText(String.format("%d", somaMedia3));
        
        txtMinimo.setText(String.format("%d", minimo));
       txtMinimo2.setText(String.format("%d", minimo2));
        txtMinimo3.setText(String.format("%d", minimo3));
        
        prgDisco.setStringPainted(true);
        prgDisco.setString(String.format("%d%%", sortear2));
        prgDisco.setForeground(Color.blue);
        prgDisco.setValue(sortear2);
        
        prgMemoria.setStringPainted(true);
         prgMemoria.setString(String.format("%d%%", sortear3));
        prgMemoria.setForeground(Color.blue);
        prgMemoria.setValue(sortear3);
    }//GEN-LAST:event_btnFazerActionPerformed

    private void txtMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximoActionPerformed

    private void txtMaximo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximo2ActionPerformed

    private void txtMaximo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximo3ActionPerformed

    private void txtMinimo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFazer;
    private javax.swing.JLabel lblCpu;
    private javax.swing.JLabel lblCpu2;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblDisco2;
    private javax.swing.JLabel lblMaximo;
    private javax.swing.JLabel lblMaximo2;
    private javax.swing.JLabel lblMaximo3;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblMedia2;
    private javax.swing.JLabel lblMedia3;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMemoria2;
    private javax.swing.JLabel lblMinimo;
    private javax.swing.JLabel lblMinimo2;
    private javax.swing.JLabel lblMinimo3;
    private javax.swing.JProgressBar prgCpu;
    private javax.swing.JProgressBar prgDisco;
    private javax.swing.JProgressBar prgMemoria;
    private javax.swing.JTextField txtMaximo;
    private javax.swing.JTextField txtMaximo2;
    private javax.swing.JTextField txtMaximo3;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextField txtMedia2;
    private javax.swing.JTextField txtMedia3;
    private javax.swing.JTextField txtMinimo;
    private javax.swing.JTextField txtMinimo2;
    private javax.swing.JTextField txtMinimo3;
    // End of variables declaration//GEN-END:variables
}
